### ISSUE TITLE
Full script for training

### ISSUE THREAD

**Issue by mamarasulovs** [yunxiangfu2001/DreamDA#3]
hi dear atuhors, thank you for awesome project. Can you provide me a full script of this project? I just want to train the model based on my idea.  Please send ur full script to this email: mamarasulovsardor@gmail.com

**Comment by yunxiangfu2001** [comment]
Sorry, I've been busy and haven't organized and cleaned all the code. I'll release the organized code on this repo ASAP.

**Comment by Liupeng-1116** [comment]
> Sorry, I've been busy and haven't organized and cleaned all the code. I'll release the organized code on this repo ASAP.
您好，我对您的工作非常感兴趣。我想尝试一下您的工作和idea，即便是未整理的代码。如果可以的话劳烦您发送至我的邮箱liupeng191116@gmail.com，我将不胜感激。

**Comment by yunxiangfu2001** [comment]
Sorry for the late response. Codes for generating images with latent perturbation and model training without AMST have been released.
